name: Docker Image CI

on:
  push:
    branches: [ "main" ]

jobs:

  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (Test Only)
        run: |
          docker build \
            --file Dockerfile \
            --tag test-build .

  build:
    runs-on: ubuntu-latest
    needs: build-test

    steps:
    - uses: actions/checkout@v4

    - name: Set up QEMU
      uses: docker/setup-qemu-action@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Docker Hub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_USERNAME" --password-stdin

    - name: Build and push multi-arch Docker image
      run: |
        VERSION=$(jq -r .version package.json)
        COMMIT_SHA=$(echo $GITHUB_SHA | cut -c1-7)
        docker buildx build \
          --platform linux/amd64,linux/arm64 \
          --file Dockerfile \
          --tag ${{ secrets.DOCKER_USERNAME }}/composecraft:${COMMIT_SHA} \
          --tag ${{ secrets.DOCKER_USERNAME }}/composecraft:${VERSION} \
          --tag ${{ secrets.DOCKER_USERNAME }}/composecraft:latest \
          --push .
