name: Docker Image CI (Test Only)

on:
  push:

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build Docker image (Test Only)
        run: |
          docker build \
            --file Dockerfile \
            --tag test-build .